name: Testes Automatizados
on:
 pull_request:
 branches: [ main ]
 push:
 branches: [ main ]
jobs:
 test:
 runs-on: ubuntu-latest
 steps:
 - name: Clonar repositório
 uses: actions/checkout@v3
 - name: Instalar dependências
 run: npm install
 - name: Rodar ESLint
 run: npx eslint