# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '43 17 * * 0'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd graphql-api-app
          npm install

      - name: List files for debug
        run: |
          cd graphql-api-app
          ls -l

      - name: Run ESLint (stdout)
        run: |
          cd graphql-api-app
          npx eslint .
        continue-on-error: true

      - name: Show ESLint config
        run: |
          cd graphql-api-app
          cat eslint.config.mjs
